(()=>{
'use strict';
const VERSION='V18.53',wikiCache=new Map(),iconPending=new Set();
function escQ(v){return encodeURIComponent(String(v||'').trim())}
async function wikiThumb(query){const key=String(query||'').trim().toLowerCase();if(!key)return'';if(wikiCache.has(key))return wikiCache.get(key);try{const url=`https://en.wikipedia.org/w/api.php?action=query&generator=search&gsrsearch=${escQ(query)}&gsrlimit=1&prop=pageimages&piprop=thumbnail&pithumbsize=500&format=json&origin=*`;const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw new Error(String(r.status));const j=await r.json(),pages=Object.values(j?.query?.pages||{}),out=String(pages[0]?.thumbnail?.source||'');wikiCache.set(key,out);return out}catch(e){wikiCache.set(key,'');return''}}
function installStyle(){const s=document.createElement('style');s.id='gfut-v1853-style';s.textContent=`.custom-card.totw{color:#f7e4a1;background:radial-gradient(circle at 68% 25%,rgba(255,220,105,.22),transparent 22%),radial-gradient(circle at 28% 68%,rgba(188,140,35,.16),transparent 31%),linear-gradient(145deg,#171817 0%,#050606 38%,#15120b 67%,#020303 100%);box-shadow:inset 0 0 0 1px rgba(246,211,105,.16)}.custom-card.totw:before{border-color:rgba(245,210,101,.72);box-shadow:inset 0 0 18px rgba(214,164,48,.12)}.custom-card.totw .pname{border-top-color:#d8b651;color:#f7e4a1}.custom-card.totw .meta,.custom-card.totw .stats{color:#e2c76f}.custom-card.totw .card-top{color:#f6dc84}.opponent-team-modal .card-shell{cursor:pointer}.opponent-team-modal .card-shell:active{transform:scale(.97)}.custom-card.icon .face img{filter:none!important}`;document.head.appendChild(s)}
function patchVersion(){document.title=document.title.replace(/V18\.\d+/,'V18.53');const b=document.querySelector('.build-badge');if(b)b.textContent=VERSION}
function patchCardClass(){if(typeof window.cardClass!=='function'||window.cardClass.__v1853)return;const old=window.cardClass,next=function(p,item){if(item?.variant==='special'&&String(item?.eventName||'').toLowerCase().includes('team of the week'))return'totw';return old(p,item)};next.__v1853=true;window.cardClass=next}
function findTotwEntryByName(name){const n=String(name||'').trim().toLowerCase();if(!n||typeof window.liveTotwTeamEntries!=='function')return null;return window.liveTotwTeamEntries().find(e=>{const a=String(e?.player?.name||e?.base?.name||'').trim().toLowerCase();return a===n||a.includes(n)||n.includes(a)})||null}
function ensureTotwBase(entry){try{if(!entry?.base||typeof P_BY_ID==='undefined'||!P_BY_ID?.set)return;if(!P_BY_ID.get(String(entry.item.pid)))P_BY_ID.set(String(entry.item.pid),entry.base)}catch(e){}}
function installTotwBioClick(){document.addEventListener('click',e=>{const modal=e.target.closest('#opponentTeamModal');if(!modal||!modal.classList.contains('active'))return;const card=e.target.closest('.card-shell');if(!card)return;const title=String(document.querySelector('#opponentTeamModalTitle')?.textContent||'').toLowerCase();if(!title.includes('team of the week'))return;const entry=findTotwEntryByName(card.querySelector('.pname')?.textContent||'');if(!entry||typeof window.openBiography!=='function')return;ensureTotwBase(entry);e.preventDefault();e.stopPropagation();window.openBiography(entry.item,-1)},true)}
function iconPool(){try{return typeof MID_ICON_BASES!=='undefined'&&Array.isArray(MID_ICON_BASES)?MID_ICON_BASES:[]}catch(e){return[]}}
function playerById(id){try{if(typeof P_BY_ID!=='undefined'&&P_BY_ID?.get)return P_BY_ID.get(String(id));if(typeof PLAYERS!=='undefined'&&Array.isArray(PLAYERS))return PLAYERS.find(x=>String(x.id)===String(id))}catch(e){}return null}
async function loadIconFace(p){if(!p||p.face||iconPending.has(p.id))return;iconPending.add(p.id);const u=await wikiThumb(`${p.name} footballer`);if(u)p.face=u;iconPending.delete(p.id);try{if(typeof window.renderMarket==='function'&&document.querySelector('#marketView.active'))window.renderMarket()}catch(e){}}
function hydrateVisibleIcons(){const pool=iconPool();document.querySelectorAll('.custom-card.icon .pname').forEach(el=>{const n=String(el.textContent||'').trim().toLowerCase(),p=pool.find(x=>String(x.name||'').trim().toLowerCase()===n);if(p&&!p.face)loadIconFace(p)})}
async function enrichAffiliation(p){if(!p)return;let changed=false;if(p.team&&!p.clubLogo){const u=await wikiThumb(`${p.team} football club`);if(u){p.clubLogo=u;changed=true}}if(p.league&&!p.leagueLogo){const u=await wikiThumb(`${p.league} football league`);if(u){p.leagueLogo=u;changed=true}}if(changed&&typeof window.refreshAffiliationDom==='function')try{window.refreshAffiliationDom()}catch(e){}}
function patchAffiliationDiscovery(){if(typeof window.ensurePlayerAffiliationAssets!=='function'||window.ensurePlayerAffiliationAssets.__v1853)return;const old=window.ensurePlayerAffiliationAssets,next=function(p){old(p);enrichAffiliation(p)};next.__v1853=true;window.ensurePlayerAffiliationAssets=next}
function hydrateVisibleAffiliations(){document.querySelectorAll('.affiliation-grid[data-player-id]').forEach(el=>{const p=playerById(el.dataset.playerId||'');if(p)enrichAffiliation(p)})}
function observe(){let t=0;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>{patchVersion();patchCardClass();patchAffiliationDiscovery();hydrateVisibleAffiliations();hydrateVisibleIcons()},80)}).observe(document.documentElement,{subtree:true,childList:true})}
function boot(){installStyle();patchVersion();patchCardClass();patchAffiliationDiscovery();installTotwBioClick();hydrateVisibleAffiliations();hydrateVisibleIcons();observe()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0),{once:true});else setTimeout(boot,0)
})();
