const assert=require("assert");
const fs=require("fs");
const path=require("path");
const root=path.resolve(__dirname,"..");
const html=fs.readFileSync(path.join(root,"index.html"),"utf8");
const css=fs.readFileSync(path.join(root,"player-profile.css"),"utf8");
assert.match(html,/<h3>Spielerprofil<\/h3>/);
assert.match(html,/function playerBiographyHTML\(/);
assert.match(html,/bio-hero-kpis/);
assert.match(html,/bio-profile-grid/);
assert.match(html,/bio-attributes-grid/);
assert.match(html,/bio-performance-grid/);
assert.match(html,/playerBiographyHTML\(b,item,\{shownPosition,clubPerf\}\)/);
assert.match(html,/playerBiographyHTML\(b,item,\{shownPosition:shown,friend:true\}\)/);
assert.match(html,/\.\/player-profile\.css\?v=2114/);
assert.match(html,/const GFUT_BUILD="V21\.17"/);
assert.match(css,/#bioModal \.bio-hero\{display:grid/);
assert.match(css,/#bioModal \.bio-attributes-grid\{display:grid;grid-template-columns:repeat\(6/);
assert.match(css,/@media\(max-width:560px\)[\s\S]*?#bioModal \.bio-profile-grid\{grid-template-columns:1fr\}/);
assert.match(css,/@media\(max-width:560px\)[\s\S]*?#bioModal \.bio-attributes-grid\{grid-template-columns:repeat\(3/);
assert.doesNotMatch(css,/^\.custom-card\s*\{/m);
assert.doesNotMatch(css,/^\.card-shell\s*\{/m);
console.log("Spielerprofil V21.17: Struktur, Mobile und Renderer-Isolation OK");
